"""Compare matched soft/hard inversions of an independently saved experiment.

From the EMTomo root, after generating and solving the forward experiment:
    python studies/compare_hypocentres.py EXPERIMENT_ID --workers 1
Or analyze a completed pair without running the solver:
    python studies/compare_hypocentres.py EXPERIMENT_ID --soft-run runs/RUN_SOFT --hard-run runs/RUN_HARD

For the recorded example, see studies/README.md and create the forward inputs
separately from the repository root:
    python -m projects.forward_modeling.hypocentre_ambiguity_example
    python -m projects.forward_modeling ambiguity24x18x12_8st_80ev_seed17 --refinement 12 --check-convergence --noise --noise-relative-sigma 0 --noise-absolute-sigma-s 0.12 --noise-seed 17
No forward inputs, arrivals, or event truth are generated by this script.
"""
from __future__ import annotations

import argparse
from dataclasses import replace
import hashlib
import json
from pathlib import Path
import sys
from uuid import uuid4

import numpy as np

# Direct invocation from the EMTomo root has studies/, not EMTomo/, on sys.path.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from experiment_data import DEFAULT_EXPERIMENTS_ROOT  # noqa: E402
from experiment_runner import prepare_inversion  # noqa: E402
from main import CONFIG, main as run_main  # noqa: E402
from tomography.tomography_em import update_velocity  # noqa: E402


EMTOMO_ROOT = Path(__file__).resolve().parents[1]


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _read_json(path: Path) -> dict:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"Expected a JSON object: {path}")
    return value


def _run_metadata(run_dir: Path) -> dict:
    meta = _read_json(run_dir / "meta.json")
    if not isinstance(meta.get("run_params"), dict) or not isinstance(meta.get("source_experiment"), dict):
        raise ValueError(f"Not a saved-experiment run: {run_dir}")
    return meta


def _check_pair(soft_dir: Path, hard_dir: Path, experiment_id: str, experiments_root: Path):
    soft, hard = _run_metadata(soft_dir), _run_metadata(hard_dir)
    for mode, meta in (("soft", soft), ("hard", hard)):
        params = meta["run_params"]
        if params.get("candidate_mode") != mode or params.get("weights_top_n", 0) < 2:
            raise ValueError(f"{mode} run must use candidate_mode={mode}, weights_top_n >= 2")
        if params.get("weight_likelihood") != "gaussian_independent_absolute_picks_marginal_origin_uniform_candidates" or params.get("normal_equations") != "station_precision_weighted_profiled_origin":
            raise ValueError(f"{mode} run does not have the expected soft/hard v1.3 likelihood and solver")
        if meta["source_experiment"].get("id") != experiment_id:
            raise ValueError(f"{mode} run refers to a different experiment")
    if soft["source_experiment"] != hard["source_experiment"]:
        raise ValueError("Run source experiments differ")
    expected_hash = _sha256(experiments_root / "input" / experiment_id / "model.npz")
    if soft["source_experiment"].get("model_sha256") != expected_hash:
        raise ValueError("Saved forward model has changed since these runs")
    if soft.get("run_version") != hard.get("run_version") or soft.get("station_locs") != hard.get("station_locs") or soft.get("grid_info") != hard.get("grid_info"):
        raise ValueError("Run versions, stations, or grids differ")
    ignored = {"candidate_mode", "run_name", "n_workers"}
    sp, hp = soft["run_params"], hard["run_params"]
    if {k: v for k, v in sp.items() if k not in ignored} != {k: v for k, v in hp.items() if k not in ignored}:
        raise ValueError("Run settings differ beyond candidate mode (or worker count/run name)")
    if not isinstance(sp.get("n_cycles"), int) or sp["n_cycles"] < 1:
        raise ValueError("Invalid n_cycles in run metadata")
    initial_soft = np.load(soft_dir / "initial_model.npy", allow_pickle=False)
    initial_hard = np.load(hard_dir / "initial_model.npy", allow_pickle=False)
    if not np.array_equal(initial_soft, initial_hard):
        raise ValueError("Initial models differ")
    return sp, expected_hash, initial_soft


def _post_update(pre: np.ndarray, delta: np.ndarray, params: dict) -> np.ndarray:
    """Match run_em's positive-slowness and velocity trust-region update."""
    if pre.shape != delta.shape or pre.ndim != 3 or not np.all(np.isfinite(pre)) or np.any(pre <= 0) or not np.all(np.isfinite(delta)):
        raise ValueError("Invalid pre-update model or slowness increment")
    # Velocity-bound parameters of pre-1.4 runs are not all persisted in meta.json;
    # fail rather than silently report incorrect RMSE when that prior was active.
    if params.get("v_reg_strength", 0) not in (0, None):
        raise ValueError("Cannot reconstruct velocity-bound regularization from run metadata")
    updated = update_velocity(pre.astype(np.float64), delta, params.get("max_velocity_step_fraction")).astype(pre.dtype)
    if not np.all(np.isfinite(updated)) or np.any(updated <= 0):
        raise ValueError("Invalid reconstructed velocity model")
    return updated


def _quality_rows(run_dir: Path, cycles: int) -> dict[int, float]:
    result = {}
    for line in (run_dir / "quality.jsonl").read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        index, value = row["iter"], row["avg_abs_pct_dev"]
        if type(index) is not int or type(value) not in (int, float) or not np.isfinite(value) or index in result:
            raise ValueError(f"Invalid/duplicate quality row: {run_dir}")
        result[index] = float(value)
    if set(result) != set(range(cycles)):
        raise ValueError(f"Incomplete quality log in {run_dir}; expected cycles 0..{cycles - 1}")
    return result


def _metrics(model: np.ndarray, reference: np.ndarray) -> tuple[float, float]:
    if model.shape != reference.shape:
        raise ValueError("Reconstructed model and reference grid shapes differ")
    diff = model - reference
    return float(np.sqrt(np.mean(diff ** 2))), float(np.mean(np.abs(diff) / reference) * 100)


def _posterior_summary(run_dir: Path, cycle: int, n_events: int, fine_side_m: float) -> dict:
    effective, rms_km, max_km, meaningful = [], [], [], []
    for event in range(n_events):
        path = run_dir / f"iter_{cycle}" / f"event_{event}" / "weights.npz"
        with np.load(path, allow_pickle=False) as saved:
            weights = np.asarray(saved["weight_values"], dtype=float)
            positions = np.asarray(saved["positions"], dtype=float)
        if (weights.ndim != 1 or weights.size < 1 or positions.shape != (weights.size, 3)
                or not np.all(np.isfinite(positions)) or not np.all(np.isfinite(weights))
                or np.any(weights < 0) or not np.isclose(weights.sum(), 1., rtol=1e-6, atol=1e-6)):
            raise ValueError(f"Invalid event weights: {path}")
        weights = weights / weights.sum()
        distances_km = np.linalg.norm((positions - positions[np.argmax(weights)]) * (fine_side_m / 1000), axis=1)
        significant = (weights > 0.01) & (distances_km > 0)
        effective.append(float(1. / np.sum(weights ** 2)))
        rms_km.append(float(np.sqrt(np.sum(weights * distances_km ** 2))))
        max_km.append(float(np.max(distances_km[significant])) if significant.any() else 0.)
        meaningful.append(bool(significant.any()))
    return {
        "n_events": n_events,
        "mean_effective_count": float(np.mean(effective)),
        "fraction_effective_count_gt_1_1": float(np.mean(np.asarray(effective) > 1.1)),
        "mean_weighted_rms_from_map_km": float(np.mean(rms_km)),
        "fraction_with_non_map_weight_gt_0_01": float(np.mean(meaningful)),
        "mean_max_non_map_separation_gt_0_01_km": float(np.mean(max_km)),
    }


def analyze(experiment_id: str, experiments_root: Path, soft_dir: Path, hard_dir: Path) -> dict:
    """Evaluate both runs against one sampled reference, never passed to the solver."""
    params, digest, initial = _check_pair(soft_dir, hard_dir, experiment_id, experiments_root)
    reference = prepare_inversion(experiment_id, replace(CONFIG, cell_size=params["coarse_side_m"]), experiments_root).reference_model.velocity
    if not np.all(np.isfinite(reference)) or np.any(reference <= 0):
        raise ValueError("Invalid reference model")
    initial_rmse, initial_mape = _metrics(initial, reference)
    cycles = params["n_cycles"]
    quality = {mode: _quality_rows(directory, cycles) for mode, directory in (("soft", soft_dir), ("hard", hard_dir))}
    previous = {"soft": initial, "hard": initial}
    rows = []
    for i in range(cycles):
        row = {"cycle": i + 1}  # cycle 1 is quality iter=0, after the first update
        for mode, directory in (("soft", soft_dir), ("hard", hard_dir)):
            pre = np.load(directory / f"iter_{i}" / "model.npy", allow_pickle=False)
            if not np.allclose(pre, previous[mode], rtol=1e-9, atol=1e-7):
                raise ValueError(f"{mode} iter_{i}/model.npy does not match preceding post-update model")
            delta = np.load(directory / f"iter_{i}" / "delta_s.npy", allow_pickle=False)
            updated = _post_update(pre, delta, params)
            rmse, mape = _metrics(updated, reference)
            if not np.isclose(mape, quality[mode][i], rtol=1e-6, atol=1e-5):
                raise ValueError(f"{mode} cycle {i + 1}: reconstructed MAPE {mape} differs from quality.jsonl {quality[mode][i]}")
            row[mode] = {"rmse_m_s": rmse, "mape_pct": mape, "logged_mape_pct": quality[mode][i]}
            previous[mode] = updated
        row["rmse_gain_m_s"] = row["hard"]["rmse_m_s"] - row["soft"]["rmse_m_s"]
        # Zero hard RMSE is possible for an exact reconstruction; avoid an undefined percentage.
        row["rmse_gain_pct_of_hard"] = (100 * row["rmse_gain_m_s"] / row["hard"]["rmse_m_s"]
                                          if row["hard"]["rmse_m_s"] > 0 else None)
        row["mape_gain_percentage_points"] = row["hard"]["mape_pct"] - row["soft"]["mape_pct"]
        row["soft_posterior"] = _posterior_summary(soft_dir, i, params["n_events"],
                                                    params["coarse_side_m"] / params["subdivision"])
        rows.append(row)
    best = max(rows, key=lambda r: r["rmse_gain_m_s"])
    generation_path = experiments_root / "input" / experiment_id / "generation.json"
    output_meta = _read_json(experiments_root / "output" / experiment_id / "metadata.json")
    return {
        "experiment_id": experiment_id,
        "source_model_sha256": digest,
        "forward_generation": _read_json(generation_path) if generation_path.exists() else None,
        "forward_noise": output_meta.get("noise"),
        "soft_run": str(soft_dir.resolve()), "hard_run": str(hard_dir.resolve()),
        "shared_run_params": {k: v for k, v in params.items() if k not in ("candidate_mode", "run_name", "n_workers")},
        "initial_rmse_m_s": initial_rmse, "initial_mape_pct": initial_mape,
        "cycles": rows,
        "predefined_terminal_cycle": rows[-1]["cycle"],
        "terminal_rmse_gain_m_s": rows[-1]["rmse_gain_m_s"],
        "terminal_rmse_gain_pct_of_hard": rows[-1]["rmse_gain_pct_of_hard"],
        "best_observed_cycle_post_hoc": best["cycle"],
        "best_observed_rmse_gain_m_s": best["rmse_gain_m_s"],
        "best_observed_rmse_gain_pct_of_hard": best["rmse_gain_pct_of_hard"],
        "reconstruction_assumption": "Optional velocity-bound regularization is off (its strength is not saved in run metadata); post-update MAPE is checked against quality.jsonl, and each next pre-update model is checked when available.",
        "interpretation": "Exploratory single saved-experiment pair; choosing the best cycle post hoc is optimistic, not evidence of general superiority. Replicate on independent saved experiments/seeds.",
    }


def positive_int(value: str) -> int:
    n = int(value)
    if n < 1:
        raise argparse.ArgumentTypeError("must be >= 1")
    return n


def cli(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("experiment_id", metavar="EXPERIMENT_ID")
    parser.add_argument("--experiments-root", type=Path, default=DEFAULT_EXPERIMENTS_ROOT)
    parser.add_argument("--runs-dir", type=Path, default=EMTOMO_ROOT / "runs", help="Ignored location for runs and JSON report")
    parser.add_argument("--soft-run", type=Path, help="Analyze an existing soft run; requires --hard-run; skip inversion")
    parser.add_argument("--hard-run", type=Path, help="Analyze an existing hard run; requires --soft-run")
    parser.add_argument("--cell-size-m", type=float, default=3000.)
    parser.add_argument("--subdivision", type=positive_int, default=6)
    parser.add_argument("--weights-top-n", type=positive_int, default=8)
    parser.add_argument("--n-candidates", type=positive_int, default=None,
                        help="Refined candidates per event (default: max(5, weights-top-n))")
    parser.add_argument("--weights-min-distance", type=positive_int, default=6, help="Fine cells; default 6 = 3 km at default resolution")
    parser.add_argument("--cycles", type=positive_int, default=7, help="Predefined terminal cycle; report also shows exploratory best cycle")
    parser.add_argument("--workers", type=positive_int, default=1)
    parser.add_argument("--temperature", type=float, default=1.)
    parser.add_argument("--weight-model-sigma-s", type=float, default=CONFIG.weight_model_sigma_s)
    parser.add_argument("--weight-noise-relative-sigma", type=float, default=None, help="Default: saved forward noise metadata")
    parser.add_argument("--weight-noise-absolute-sigma-s", type=float, default=None, help="Default: saved forward noise metadata")
    parser.add_argument("--lambda-reg", type=float, default=CONFIG.lambda_reg)
    parser.add_argument("--coverage-damping-power", type=float, default=CONFIG.coverage_damping_power)
    parser.add_argument("--max-velocity-step-fraction", type=float, default=CONFIG.max_velocity_step_fraction)
    args = parser.parse_args(argv)
    if (args.soft_run is None) != (args.hard_run is None):
        parser.error("--soft-run and --hard-run must be supplied together")
    if args.soft_run is None:
        if args.weights_top_n < 2:
            parser.error("--weights-top-n must be at least 2 for a soft/hard comparison")
        for name in ("cell_size_m", "temperature"):
            if not np.isfinite(getattr(args, name)) or getattr(args, name) <= 0:
                parser.error(f"--{name.replace('_', '-')} must be positive and finite")
        for name in ("weight_model_sigma_s", "weight_noise_relative_sigma", "weight_noise_absolute_sigma_s", "lambda_reg", "coverage_damping_power"):
            value = getattr(args, name)
            if value is not None and (not np.isfinite(value) or value < 0):
                parser.error(f"--{name.replace('_', '-')} must be finite and nonnegative")
        if not np.isfinite(args.max_velocity_step_fraction) or not 0 <= args.max_velocity_step_fraction < 1:
            parser.error("--max-velocity-step-fraction must be in [0, 1)")
    try:
        if args.soft_run is not None:
            soft_dir, hard_dir = args.soft_run, args.hard_run
        else:
            config = replace(
                CONFIG, cell_size=args.cell_size_m, subdivision=args.subdivision,
                n_candidates=args.n_candidates or max(CONFIG.n_candidates, args.weights_top_n),
                weights_top_n=args.weights_top_n, weights_min_distance=args.weights_min_distance,
                n_cycles=args.cycles, n_workers=args.workers, temperature=args.temperature,
                weight_noise_relative_sigma=args.weight_noise_relative_sigma,
                weight_noise_absolute_sigma_s=args.weight_noise_absolute_sigma_s,
                weight_model_sigma_s=args.weight_model_sigma_s, lambda_reg=args.lambda_reg,
                coverage_damping_power=args.coverage_damping_power,
                max_velocity_step_fraction=args.max_velocity_step_fraction, runs_dir=str(args.runs_dir),
                run_name="hypocentre-pair", save_runs=True,
            )
            # Validate the saved experiment and setup before starting either expensive run.
            run_main(config, experiment_id=args.experiment_id, experiments_root=args.experiments_root, validate_only=True)
            completed = {}
            for mode in ("hard", "soft"):
                logger = run_main(replace(config, candidate_mode=mode), experiment_id=args.experiment_id,
                                  experiments_root=args.experiments_root)
                completed[mode] = logger.run_dir
                print(f"Completed {mode}: {logger.run_dir}", flush=True)
            soft_dir, hard_dir = completed["soft"], completed["hard"]
        report = analyze(args.experiment_id, args.experiments_root, soft_dir, hard_dir)
        args.runs_dir.mkdir(parents=True, exist_ok=True)
        destination = args.runs_dir / f"hypocentre_comparison_{uuid4().hex}.json"
        with destination.open("x", encoding="utf-8") as stream:
            json.dump(report, stream, indent=2, allow_nan=False)
            stream.write("\n")
    except (OSError, ValueError, KeyError, IndexError) as error:
        parser.exit(1, f"{parser.prog}: {error}\n")
    terminal = report["cycles"][-1]
    print(f"Report: {destination}\nInitial RMSE: {report['initial_rmse_m_s']:.3f} m/s")
    for row in report["cycles"]:
        gain_pct = (f"{row['rmse_gain_pct_of_hard']:+.2f}%"
                    if row['rmse_gain_pct_of_hard'] is not None else "n/a (hard RMSE is zero)")
        print(f"Cycle {row['cycle']}: soft {row['soft']['rmse_m_s']:.3f}, hard {row['hard']['rmse_m_s']:.3f} m/s; "
              f"soft gain {row['rmse_gain_m_s']:+.3f} m/s ({gain_pct}); "
              f"MAPE soft/hard {row['soft']['mape_pct']:.3f}/{row['hard']['mape_pct']:.3f}%; "
              f"soft effective K {row['soft_posterior']['mean_effective_count']:.2f}")
    best = report["best_observed_rmse_gain_m_s"]
    print(f"Predefined terminal cycle {terminal['cycle']} gain: {terminal['rmse_gain_m_s']:+.3f} m/s; "
          f"best observed (post hoc) cycle {report['best_observed_cycle_post_hoc']}: {best:+.3f} m/s.")
    if best <= 0:
        print("No observed soft RMSE gain over hard in this pair.")
    print("Exploratory single pair, not proof; replicate on independent saved experiments/seeds.")
    return 0


if __name__ == "__main__":
    raise SystemExit(cli())
