events {}

http {
  access_log /dev/stdout;
  error_log /dev/stderr notice;

  server {
    listen 80;
    server_name _;
    absolute_redirect off;

    location = / {
      return 302 /main.pdf;
    }

    location = /main.pdf {
      alias /srv/main.pdf;
      default_type application/pdf;
      add_header Cache-Control "no-store";
      add_header Content-Disposition "inline";
    }

    location / {
      return 404;
    }
  }
}
